In [1]:
#量子化テーブルの作成
import numpy as np

table = np.zeros((8,8,8))
for i in range(8):
    for j in range(8):
        for k in range(8):
            table[i,j,k] = (2*(i+1)) * (2*(j+1)) * (2*(k+1))+ (i+1)*(j+1)*(k+1)
table += 100
print(table)

[[[ 109.  118.  127.  136.  145.  154.  163.  172.]
  [ 118.  136.  154.  172.  190.  208.  226.  244.]
  [ 127.  154.  181.  208.  235.  262.  289.  316.]
  [ 136.  172.  208.  244.  280.  316.  352.  388.]
  [ 145.  190.  235.  280.  325.  370.  415.  460.]
  [ 154.  208.  262.  316.  370.  424.  478.  532.]
  [ 163.  226.  289.  352.  415.  478.  541.  604.]
  [ 172.  244.  316.  388.  460.  532.  604.  676.]]

 [[ 118.  136.  154.  172.  190.  208.  226.  244.]
  [ 136.  172.  208.  244.  280.  316.  352.  388.]
  [ 154.  208.  262.  316.  370.  424.  478.  532.]
  [ 172.  244.  316.  388.  460.  532.  604.  676.]
  [ 190.  280.  370.  460.  550.  640.  730.  820.]
  [ 208.  316.  424.  532.  640.  748.  856.  964.]
  [ 226.  352.  478.  604.  730.  856.  982. 1108.]
  [ 244.  388.  532.  676.  820.  964. 1108. 1252.]]

 [[ 127.  154.  181.  208.  235.  262.  289.  316.]
  [ 154.  208.  262.  316.  370.  424.  478.  532.]
  [ 181.  262.  343.  424.  505.  586.  667.  748.]
  [ 208.

In [3]:
#８×８×８画像の作成
#グラデーションが動くような感じ
#photoshopで少しずつずらして8枚の画像をつくる
#OpenCVで色データを読み取る
#次回ミーティングまでに，三次元画像を，DCT,量子化，IDCTして復元して目視で確認するところまでやる
import numpy as np
import matplotlib.pyplot as plt
import scipy
import cv2

"""
img1 = cv2.imread("yoko.bmp")
img2 = cv2.imread("yoko.bmp")
img3 = cv2.imread("yoko.bmp")
img4 = cv2.imread("yoko.bmp")
img5 = cv2.imread("yoko.bmp")
img6 = cv2.imread("yoko.bmp")
img7 = cv2.imread("yoko.bmp")
img8 = cv2.imread("yoko.bmp")
"""
"""
img1 = cv2.imread("1.bmp")
img2 = cv2.imread("2.bmp")
img3 = cv2.imread("3.bmp")
img4 = cv2.imread("4.bmp")
img5 = cv2.imread("5.bmp")
img6 = cv2.imread("6.bmp")
img7 = cv2.imread("7.bmp")
img8 = cv2.imread("8.bmp")
"""

img1 = cv2.imread("11.bmp")
img2 = cv2.imread("22.bmp")
img3 = cv2.imread("33.bmp")
img4 = cv2.imread("44.bmp")
img5 = cv2.imread("55.bmp")
img6 = cv2.imread("66.bmp")
img7 = cv2.imread("77.bmp")
img8 = cv2.imread("88.bmp")

"""
cv2.namedWindow("Image1", cv2.WINDOW_NORMAL)
cv2.namedWindow("Image2", cv2.WINDOW_NORMAL)
cv2.namedWindow("Image3", cv2.WINDOW_NORMAL)
cv2.namedWindow("Image4", cv2.WINDOW_NORMAL)
cv2.namedWindow("Image5", cv2.WINDOW_NORMAL)
cv2.namedWindow("Image6", cv2.WINDOW_NORMAL)
cv2.namedWindow("Image7", cv2.WINDOW_NORMAL)
cv2.namedWindow("Image8", cv2.WINDOW_NORMAL)
cv2.imshow("Image1", img1)
cv2.imshow("Image2", img2)
cv2.imshow("Image3", img3)
cv2.imshow("Image4", img4)
cv2.imshow("Image5", img5)
cv2.imshow("Image6", img6)
cv2.imshow("Image7", img7)
cv2.imshow("Image8", img8)
cv2.waitKey()
"""
#YCrCbに変換
img1_YCrCb = cv2.cvtColor(img1,cv2.COLOR_BGR2YCrCb)
img2_YCrCb = cv2.cvtColor(img2,cv2.COLOR_BGR2YCrCb)
img3_YCrCb = cv2.cvtColor(img3,cv2.COLOR_BGR2YCrCb)
img4_YCrCb = cv2.cvtColor(img4,cv2.COLOR_BGR2YCrCb)
img5_YCrCb = cv2.cvtColor(img5,cv2.COLOR_BGR2YCrCb)
img6_YCrCb = cv2.cvtColor(img6,cv2.COLOR_BGR2YCrCb)
img7_YCrCb = cv2.cvtColor(img7,cv2.COLOR_BGR2YCrCb)
img8_YCrCb = cv2.cvtColor(img8,cv2.COLOR_BGR2YCrCb)
#成分ごとに分割
img1_Y, img1_Cr, img1_Cb = cv2.split(img1_YCrCb)
img2_Y, img2_Cr, img2_Cb = cv2.split(img2_YCrCb)
img3_Y, img3_Cr, img3_Cb = cv2.split(img3_YCrCb)
img4_Y, img4_Cr, img4_Cb = cv2.split(img4_YCrCb)
img5_Y, img5_Cr, img5_Cb = cv2.split(img5_YCrCb)
img6_Y, img6_Cr, img6_Cb = cv2.split(img6_YCrCb)
img7_Y, img7_Cr, img7_Cb = cv2.split(img7_YCrCb)
img8_Y, img8_Cr, img8_Cb = cv2.split(img8_YCrCb)

#統合(Y成分)
img_Y = np.zeros((8,8,8))
img_Y[0] = img1_Y
img_Y[1] = img2_Y
img_Y[2] = img3_Y
img_Y[3] = img4_Y
img_Y[4] = img5_Y
img_Y[5] = img6_Y
img_Y[6] = img7_Y
img_Y[7] = img8_Y
#print(img_Y)

#統合(Cr成分)
img_Cr = np.zeros((8,8,8))
img_Cr[0] = img1_Cr
img_Cr[1] = img2_Cr
img_Cr[2] = img3_Cr
img_Cr[3] = img4_Cr
img_Cr[4] = img5_Cr
img_Cr[5] = img6_Cr
img_Cr[6] = img7_Cr
img_Cr[7] = img8_Cr
#print(img_Cr)

#統合(Cb成分)
img_Cb = np.zeros((8,8,8))
img_Cb[0] = img1_Cb
img_Cb[1] = img2_Cb
img_Cb[2] = img3_Cb
img_Cb[3] = img4_Cb
img_Cb[4] = img5_Cb
img_Cb[5] = img6_Cb
img_Cb[6] = img7_Cb
img_Cb[7] = img8_Cb
print(img_Cb)





[[[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[128. 128. 128. 128. 128. 128. 128. 128.]
  [128. 128. 128. 128. 128. 128. 128. 128.]
  [128. 128. 128. 128. 128. 128. 128. 128.]
  [128. 128. 128. 128. 128. 128. 128. 128.]
  [128. 128. 128. 128. 128. 128. 128. 128.]
  [128. 128. 128. 128. 128. 128. 128. 128.]
  [128. 128. 128. 128. 128. 128. 128. 128.]
  [128. 128. 128. 128. 128. 128. 128

In [4]:
#DCTIDCT

import numpy as np
import matplotlib.pyplot as plt

#コサイン定数の定義
C13 = -0.831469612
C9 = -0.195090322
C5 = 0.555570233

"""
C13 = -0.8
C9 = -0.2
C5 = 0.5
"""
#近い分数を調べてそれでやればいい？
#いや，intにするときの丸め誤差の方が大きい気がする
#それでもやらないとだめ
#丸め誤差があっても逆Cでずれなければ大丈夫な可能性

#課題：ハードウェアでやる場合の誤差伝搬をどう少なくするか

C5_inv = 1 / C5
C9_inv = 1 / C9
C13_inv = 1 / C13

print(C5_inv)
print(C9_inv)
print(C13_inv)

#8*8*8を生成(8*8の同じ画像を8枚)
#ランダム
"""
x_in1 = np.random.rand(8,8,8)*255
x_in1 = x_in1.astype(np.int64)
"""
#自作
Y = np.copy(img_Y)
Cr = np.copy(img_Cr)
Cb = np.copy(img_Cb)

X_out1 = np.zeros((8,8,8))
X_out2 = np.zeros((8,8,8))
X_out3 = np.zeros((8,8,8))
x_in2 = np.zeros((8,8,8))
x_in3 = np.zeros((8,8,8))
x_in3i = np.zeros((8,8,8))
x_in2i = np.zeros((8,8,8))
x_in1i = np.zeros((8,8,8))
X_out1i = np.zeros((8,8,8))
X_out2i = np.zeros((8,8,8))


def butterfly_1(x):
    X = np.zeros(8)
    X[0] = x[0] + x[1]
    X[1] = x[2] + x[3]
    X[2] = x[0] - x[1]
    X[3] = x[2] - x[3]
    X[4] = x[4] + x[5]
    X[5] = x[6] + x[7]
    X[6] = x[4] - x[5]
    X[7] = x[6] - x[7]
    return X

def butterfly_2(x):
    X = np.zeros(8)
    X[0] = x[0] + x[1]
    X[1] = x[4] + x[5]
    X[2] = x[2] + x[3]
    X[3] = x[6] + x[7]
    X[4] = x[0] - x[1]
    X[5] = x[4] - x[5]
    X[6] = x[2] - x[3]
    X[7] = x[6] - x[7]
    return X

def butterfly_3(x):
    X = np.zeros(8)
    X[0] = x[0] + x[1]
    X[1] = x[0] - x[1]
    X[2] = x[2] + x[3]
    X[3] = x[2] - x[3]
    X[4] = x[4] + x[5]
    X[5] = x[4] - x[5]
    X[6] = x[6] + x[7]
    X[7] = x[6] - x[7]
    return X

def cosine(x):
    X = np.zeros(8)
    X[0] = x[0]
    X[1] = x[1]*C13
    X[2] = x[2]*C9
    X[3] = x[3]*C9*C13
    X[4] = x[4]*C5
    X[5] = x[5]*C13*C5
    X[6] = x[6]*C9*C5
    X[7] = x[7]*C13*C9*C5
    return X

def Ibutterfly_1(X):
    x = np.zeros(8)
    x[0] = 0.5*(X[0] + X[2])
    x[1] = 0.5*(X[0] - X[2])
    x[2] = 0.5*(X[1] + X[3])
    x[3] = 0.5*(X[1] - X[3])
    x[4] = 0.5*(X[4] + X[6])
    x[5] = 0.5*(X[4] - X[6])
    x[6] = 0.5*(X[5] + X[7])
    x[7] = 0.5*(X[5] - X[7])
    return x

def Ibutterfly_2(X):
    x = np.zeros(8)
    x[0] = (X[0] + X[4]) / 2.0
    x[1] = (X[0] - X[4]) / 2.0
    x[2] = (X[2] + X[6]) / 2.0
    x[3] = (X[2] - X[6]) / 2.0
    x[4] = (X[1] + X[5]) / 2.0
    x[5] = (X[1] - X[5]) / 2.0
    x[6] = (X[3] + X[7]) / 2.0
    x[7] = (X[3] - X[7]) / 2.0
    return x

def Ibutterfly_3(X):
    x = np.zeros(8)
    x[0] = 0.5 * (X[0] + X[1])
    x[1] = 0.5 * (X[0] - X[1])
    x[2] = 0.5 * (X[2] + X[3])
    x[3] = 0.5 * (X[2] - X[3])
    x[4] = 0.5 * (X[4] + X[5])
    x[5] = 0.5 * (X[4] - X[5])
    x[6] = 0.5 * (X[6] + X[7])
    x[7] = 0.5 * (X[6] - X[7])
    return x

def inv_cosine(X):
    x = np.zeros(8)
    x[0] = X[0]
    x[1] = X[1] * C13_inv
    x[2] = X[2] * C9_inv
    x[3] = X[3] * (C9_inv * C13_inv)
    x[4] = X[4] * C5_inv
    x[5] = X[5] * (C5_inv * C13_inv)
    x[6] = X[6] * (C5_inv * C9_inv)
    x[7] = X[7] * (C5_inv * C9_inv * C13_inv)
    return x

def DCT1(x_in):
    X_1 = butterfly_1(x_in)
    X_2 = butterfly_2(X_1)
    X_3 = butterfly_3(X_2)
    X_out = cosine(X_3)
    return X_out

def IDCT1(X_out):
    X_3 = inv_cosine(X_out)
    X_2 = Ibutterfly_3(X_3)
    X_1 = Ibutterfly_2(X_2)
    x = Ibutterfly_1(X_1)
    return x

def DCT(x_in):
    for i in range(8):
        x = x_in[i]
        X_out = DCT1(x)
        x_in[i] = X_out
    return x_in
    
def IDCT(X_out):
    for i in range(8):
        X = X_out[i]
        x = IDCT1(X)
        X_out[i] = x
    return X_out

def tenchi(x):
    for i in range(8):
        x[i] = np.transpose(x[i])
    return x

def DCT_3D(x_in1, X_out1, x_in2, X_out2, x_in3, X_out3):
    # ｘ方向   
    for i in range(8):
        X_out1[i] = DCT(x_in1[i])
    #転置
    x_in2 = tenchi(X_out1)
    #ｙ方向
    for i in range(8):
        X_out2[i] = DCT(x_in2[i])
    #ｚ方向
    x_in3 = np.copy(X_out2)
    x_in3 = np.rot90(x_in3, 1, axes=(2,0))
    for i in range(8):
        X_out3[i] = DCT(x_in3[i])
    #X_out3 = np.rot90(X_out3, -1, axes=(2,0)) #元に戻す回転（あえてやる必要はない）
    X_out3 = X_out3.astype(np.int64)
    #print(X_out3)
    return X_out3

def IDCT_3D(X_out3, x_in3i, X_out2i, x_in2i, X_out1i, x_in1i):
    #z方向
    for i in range(8):
        x_in3i[i] = IDCT(X_out3[i])
    x_in3i = np.rot90(x_in3i, -1, axes=(2,0))
    X_out2i = np.copy(x_in3i)
    #y方向
    for i in range(8):
        x_in2i[i] = IDCT(X_out2i[i])
    #転置
    X_out1i = tenchi(x_in2i)
    # ｘ方向   
    for i in range(8):
        x_in1i[i] = IDCT(X_out1i[i])
    x_in1i = x_in1i.astype(np.int64)
    #print(x_in1i)
    return x_in1i

#変換
#Y
#DCT
X_out3 = DCT_3D(Y, X_out1, x_in2, X_out2, x_in3, X_out3)
#量子化
print(X_out3)
X_out3 = X_out3/table
X_out3 = X_out3.astype(np.int64)
X_out3 = X_out3*table
#IDCT
Y_recrypt = IDCT_3D(X_out3, x_in3i, X_out2i, x_in2i, X_out1i, x_in1i)

#Cr
X_out3 = DCT_3D(Cr, X_out1, x_in2, X_out2, x_in3, X_out3)
#量子化
X_out3 = X_out3/table
X_out3 = X_out3.astype(np.int64)
X_out3 = X_out3*table
Cr_recrypt = IDCT_3D(X_out3, x_in3i, X_out2i, x_in2i, X_out1i, x_in1i)

#Cb
X_out3 = DCT_3D(Cb, X_out1, x_in2, X_out2, x_in3, X_out3)
#量子化
X_out3 = X_out3/table
X_out3 = X_out3.astype(np.int64)
zigzag = np.copy(X_out3)
X_out3 = X_out3*table
Cb_recrypt = IDCT_3D(X_out3, x_in3i, X_out2i, x_in2i, X_out1i, x_in1i)

"""
#確認
x_dif = np.zeros((8,8,8))
x_dif = img_Cb - Cb_recrypt
x_dif = x_dif.astype(np.int32)
#print(img_Y)
#print(Cb_recrypt)
print(x_dif)
"""

#DCTの段階ごとにIDCTと比較する

#DCTも一つの関数にする

#量子化テーブルを，DCTの結果とJPGをもとに作成する
#圧縮・通信方式を考える

#画像の表示方法

1.7999524463363394
-5.125830895906769
-1.202689774307711
[[[11552     0     0  -887     0   280   593     0]
  [    0     0     0     0     0     0     0     0]
  [    0     0     0     0     0     0     0     0]
  [ -887     0     0    47     0  -136   -32     0]
  [    0     0     0     0     0     0     0     0]
  [  280     0     0  -136     0  -648    91     0]
  [  593     0     0   -32     0    91    21     0]
  [    0     0     0     0     0     0     0     0]]

 [[    0     0     0     0     0     0     0     0]
  [    0     0     0     0     0     0     0     0]
  [    0     0     0     0     0     0     0     0]
  [    0     0     0     0     0     0     0     0]
  [    0     0     0     0     0     0     0     0]
  [    0     0     0     0     0     0     0     0]
  [    0     0     0     0     0     0     0     0]
  [    0     0     0     0     0     0     0     0]]

 [[    0     0     0     0     0     0     0     0]
  [    0     0     0     0     0     0     0     0]
  [

'\n#確認\nx_dif = np.zeros((8,8,8))\nx_dif = img_Cb - Cb_recrypt\nx_dif = x_dif.astype(np.int32)\n#print(img_Y)\n#print(Cb_recrypt)\nprint(x_dif)\n'

In [5]:
#表示
import cv2

Y_recrypt[Y_recrypt<0] = 0
Cr_recrypt[Cr_recrypt<0] = 0
Cb_recrypt[Cb_recrypt<0] = 0
Y_recrypt = Y_recrypt.astype(np.uint8)
Cr_recrypt = Cr_recrypt.astype(np.uint8)
Cb_recrypt = Cb_recrypt.astype(np.uint8)


merge_YCrCb_1 = cv2.merge((Y_recrypt[0], Cr_recrypt[0], Cb_recrypt[0]))
merge_1 = cv2.cvtColor(merge_YCrCb_1,cv2.COLOR_YCrCb2BGR)
merge_YCrCb_2 = cv2.merge((Y_recrypt[1], Cr_recrypt[1], Cb_recrypt[1]))
merge_2 = cv2.cvtColor(merge_YCrCb_2,cv2.COLOR_YCrCb2BGR)
merge_YCrCb_3 = cv2.merge((Y_recrypt[2], Cr_recrypt[2], Cb_recrypt[2]))
merge_3 = cv2.cvtColor(merge_YCrCb_3,cv2.COLOR_YCrCb2BGR)

"""
cv2.namedWindow("Image0", cv2.WINDOW_NORMAL)
cv2.imshow("Image0", merge_0)
cv2.namedWindow("Image1", cv2.WINDOW_NORMAL)
cv2.imshow("Image1", merge_1)
"""
cv2.namedWindow("Image2re", cv2.WINDOW_NORMAL)
cv2.imshow("Image2re", merge_3)
cv2.namedWindow("Image2", cv2.WINDOW_NORMAL)
cv2.imshow("Image2", img3)
cv2.waitKey()

-1

In [6]:
#ジグザグに並べる

zigzag = zigzag.astype(np.int32)
print(zigzag)

[[[541   0   0   3   0  -1  -2   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  3   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [ -1   0   0   0   0   0   0   0]
  [ -2   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]]

 [[  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]]

 [[  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]]

 [[  3   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0   0   0   0]
  [  0   0   0   0   0

In [140]:
#IDCT
#デバッグ用
import numpy as np
import matplotlib.pyplot as plt

#コサイン定数の定義
C13 = -0.831469612
C9 = -0.195090322
C5 = 0.555570233

C5_inv = 1 / C5
C9_inv = 1 / C9
C13_inv = 1 / C13

print(C5_inv)
print(C9_inv)
print(C13_inv)

#8*8*8を生成(8*8の同じ画像を8枚)
x_in1 = np.random.rand(8,8,8)*255
#x_in = np.stack([x_in, x_in, x_in, x_in, x_in, x_in, x_in, x_in])
x_in1 = x_in1.astype(np.int64)
X_out1 = np.zeros((8,8,8))
X_out2 = np.zeros((8,8,8))
X_out3 = np.zeros((8,8,8))
x_in3 = np.zeros((8,8,8))
x_in3i = np.zeros((8,8,8))
x_in2i = np.zeros((8,8,8))
x_in1i = np.zeros((8,8,8))
x_out1i = np.zeros((8,8,8))
x_out2i = np.zeros((8,8,8))

def butterfly_1(x):
    X = np.zeros(8)
    X[0] = x[0] + x[1]
    X[1] = x[2] + x[3]
    X[2] = x[0] - x[1]
    X[3] = x[2] - x[3]
    X[4] = x[4] + x[5]
    X[5] = x[6] + x[7]
    X[6] = x[4] - x[5]
    X[7] = x[6] - x[7]
    return X

def butterfly_2(x):
    X = np.zeros(8)
    X[0] = x[0] + x[1]
    X[1] = x[4] + x[5]
    X[2] = x[2] + x[3]
    X[3] = x[6] + x[7]
    X[4] = x[0] - x[1]
    X[5] = x[4] - x[5]
    X[6] = x[2] - x[3]
    X[7] = x[6] - x[7]
    return X

def butterfly_3(x):
    X = np.zeros(8)
    X[0] = x[0] + x[1]
    X[1] = x[0] - x[1]
    X[2] = x[2] + x[3]
    X[3] = x[2] - x[3]
    X[4] = x[4] + x[5]
    X[5] = x[4] - x[5]
    X[6] = x[6] + x[7]
    X[7] = x[6] - x[7]
    return X

def cosine(x):
    X = np.zeros(8)
    X[0] = x[0]
    X[1] = x[1]*C13
    X[2] = x[2]*C9
    X[3] = x[3]*C9*C13
    X[4] = x[4]*C5
    X[5] = x[5]*C13*C5
    X[6] = x[6]*C9*C5
    X[7] = x[7]*C13*C9*C5
    return X

def Ibutterfly_1(X):
    x = np.zeros(8)
    x[0] = 0.5*(X[0] + X[2])
    x[1] = 0.5*(X[0] - X[2])
    x[2] = 0.5*(X[1] + X[3])
    x[3] = 0.5*(X[1] - X[3])
    x[4] = 0.5*(X[4] + X[6])
    x[5] = 0.5*(X[4] - X[6])
    x[6] = 0.5*(X[5] + X[7])
    x[7] = 0.5*(X[5] - X[7])
    return x

def Ibutterfly_2(X):
    x = np.zeros(8)
    x[0] = 0.5 * (X[0] + X[4])
    x[1] = 0.5 * (X[0] - X[4])
    x[2] = 0.5 * (X[2] + X[6])
    x[3] = 0.5 * (X[2] - X[6])
    x[4] = 0.5 * (X[1] + X[5])
    x[5] = 0.5 * (X[1] - X[5])
    x[6] = 0.5 * (X[3] + X[7])
    x[7] = 0.5 * (X[3] - X[7])
    return x

def Ibutterfly_3(X):
    x = np.zeros(8)
    x[0] = 0.5 * (X[0] + X[1])
    x[1] = 0.5 * (X[0] - X[1])
    x[2] = 0.5 * (X[2] + X[3])
    x[3] = 0.5 * (X[2] - X[3])
    x[4] = 0.5 * (X[4] + X[5])
    x[5] = 0.5 * (X[4] - X[5])
    x[6] = 0.5 * (X[6] + X[7])
    x[7] = 0.5 * (X[6] - X[7])
    return x

def inv_cosine(X):
    x = np.zeros(8)
    x[0] = X[0]
    x[1] = X[1] * C13_inv
    x[2] = X[2] * C9_inv
    x[3] = X[3] * (C9_inv * C13_inv)
    x[4] = X[4] * C5_inv
    x[5] = X[5] * (C5_inv * C13_inv)
    x[6] = X[6] * (C5_inv * C9_inv)
    x[7] = X[7] * (C5_inv * C9_inv * C13_inv)
    return x

def DCT1(x_in):
    X_1 = x_in
    #X_1 = butterfly_1(x_in)
    X_2 = X_1
    X_2 = butterfly_2(X_1)
    X_3 = butterfly_3(X_2)
    X_out = cosine(X_3)
    return X_out

def IDCT1(X_out):
    X_3 = inv_cosine(X_out)
    X_2 = Ibutterfly_3(X_3)
    X_1 = Ibutterfly_2(X_2)
    x = X_1
    #x = Ibutterfly_1(X_1)
    return x

def DCT(x_in):
    for i in range(8):
        x = x_in[i]
        X_out = DCT1(x)
        x_in[i] = X_out
    return x_in
    
def IDCT(X_out):
    for i in range(8):
        X = X_out[i]
        x = IDCT1(X)
        X_out[i] = x
    return X_out

def tenchi(x):
    for i in range(8):
        x[i] = np.transpose(x[i])
    return x


#print(x_in1)
x_before = np.zeros((8,8,8))
x_before = np.copy(x_in1)

#ＤＣＴを実行 
# ｘ方向   
for i in range(8):
    X_out1[i] = DCT(x_in1[i])

"""
#転置
x_in2 = tenchi(X_out1)
#ｙ方向
for i in range(8):
    X_out2[i] = DCT(x_in2[i])
#ｚ方向
x_in3 = np.copy(X_out2)
x_in3 = np.rot90(x_in3, 1, axes=(2,0))
for i in range(8):
    X_out3[i] = DCT(x_in3[i])
#X_out3 = np.rot90(X_out3, -1, axes=(2,0)) #元に戻す回転（あえてやる必要はない）
X_out3 = X_out3.astype(np.int64)

#IDCTを実行
#z方向
for i in range(8):
    x_in3i[i] = IDCT(X_out3[i])
x_in3i = np.rot90(x_in3i, -1, axes=(2,0))
X_out2i = np.copy(x_in3i)
#y方向
for i in range(8):
    x_in2i[i] = IDCT(X_out2i[i])
#転置
X_out1i = tenchi(x_in2i)
"""

X_out1i = np.copy(X_out1)

# ｘ方向   
for i in range(8):
    x_in1i[i] = IDCT(X_out1i[i])
x_in1i = x_in1i.astype(np.int64)

x_dif = np.zeros((8,8,8))
x_dif = x_before - x_in1i
x_dif = x_dif.astype(np.int32)
#print(x_before)
#print(x_in1i)
print(x_dif)

#DCTの段階ごとにIDCTと比較する

1.7999524463363394
-5.125830895906769
-1.202689774307711
[[[ 1  0  1  2  1  1  2 -2]
  [ 0  1  3 -1  1  0  1  3]
  [ 0  1  0  3  1  0  0  2]
  [ 1  0  1  4  0  1  0  0]
  [ 0  1  5 -1  0  1 -2  1]
  [ 1  0  0  5  0  1  1 -1]
  [ 0  1 -1  0  1  0  1  2]
  [ 0  1 -2  5  1  0  3  0]]

 [[ 0  1  1  3  1  0 -1  5]
  [ 1  0  3  0  0  1 -3  3]
  [ 1  0  4 -2  0  1  2  1]
  [ 0  0  0  3  1  1  3 -2]
  [ 1  0  0 -1  0  1 -1  5]
  [ 1  1  0  2  0  1  2 -1]
  [ 1  0  4  0  0  0 -2  3]
  [ 1 -1  4 -1  1  1  2 -1]]

 [[ 1  0 -1  2  1  1  2  1]
  [ 0  1 -3  3  1  0  3  2]
  [ 1  1 -1  3  0  0  6  0]
  [ 1  0 -1  4  0  1  1  2]
  [ 0  1 -2  4  1  0  4  0]
  [ 0  1  1  3  1  0  3 -2]
  [ 1  1  4 -1  1  0 -1  2]
  [ 0  1 -3  5  1  0  2  0]]

 [[ 1  0  0  3  1  1  1  2]
  [ 0  1  1  0  1  0  3  1]
  [ 1  0  2  3  0  1 -3  4]
  [ 0  1  3  0  1  1  4  0]
  [ 0  0  2 -2  0  1  3  3]
  [ 0  0  0  4  1  1  1 -1]
  [ 0  0 -2  6  1  0  1  1]
  [ 0  0  2  2  0  1  0 -2]]

 [[ 0  1  4 -1  1  1 -1 -1]
  [ 0  1 -1