In [1]:
import numpy as np
import matplotlib.pyplot as plt
import scipy
import cv2

#画像読み込み
img = cv2.imread("1616_grad.bmp")

#画像の分割処理
rows = 2  # 行数
cols = 2  # 列数

chunks = []
for row_img in np.array_split(img, rows, axis=0):
    for chunk in np.array_split(row_img, cols, axis=1):
        chunks.append(chunk)

#print(img)
split11 = chunks[0]
split12 = chunks[1]
split21 = chunks[2]
split22 = chunks[3]

print(split11)

#分割した画像の表示
cv2.namedWindow("Image1", cv2.WINDOW_NORMAL)
cv2.namedWindow("Image2", cv2.WINDOW_NORMAL)
cv2.namedWindow("Image3", cv2.WINDOW_NORMAL)
cv2.namedWindow("Image4", cv2.WINDOW_NORMAL)
cv2.imshow("Image1", split11)
cv2.imshow("Image2", split12)
cv2.imshow("Image3", split21)
cv2.imshow("Image4", split22)
cv2.waitKey()


[[[117 136 134]
  [120 133 134]
  [123 130 135]
  [127 127 135]
  [131 124 137]
  [134 120 137]
  [138 117 139]
  [142 114 141]]

 [[115 139 137]
  [118 136 137]
  [121 134 138]
  [125 130 138]
  [129 127 139]
  [132 123 141]
  [136 120 143]
  [140 117 143]]

 [[112 143 139]
  [116 140 139]
  [119 137 140]
  [122 134 141]
  [126 130 143]
  [129 127 143]
  [133 124 145]
  [138 120 147]]

 [[110 147 143]
  [114 143 143]
  [116 140 144]
  [120 137 144]
  [124 135 145]
  [127 131 146]
  [131 127 147]
  [135 124 150]]

 [[107 150 144]
  [110 147 145]
  [113 143 146]
  [117 141 147]
  [120 137 149]
  [125 134 150]
  [129 131 151]
  [132 127 152]]

 [[105 153 148]
  [107 150 149]
  [111 147 149]
  [115 144 151]
  [118 141 151]
  [122 138 152]
  [126 135 154]
  [130 131 156]]

 [[101 156 151]
  [105 154 151]
  [108 152 153]
  [111 148 153]
  [116 145 154]
  [119 143 156]
  [123 138 157]
  [127 135 158]]

 [[ 99 160 154]
  [102 157 154]
  [106 155 155]
  [109 152 156]
  [113 149 157]
  [116 145

-1

In [44]:
#split11についてデータ列を表示
# バイナリ変換
split_bin = split11.flatten()
print(split_bin)


[117 136 134 120 133 134 123 130 135 127 127 135 131 124 137 134 120 137
 138 117 139 142 114 141 115 139 137 118 136 137 121 134 138 125 130 138
 129 127 139 132 123 141 136 120 143 140 117 143 112 143 139 116 140 139
 119 137 140 122 134 141 126 130 143 129 127 143 133 124 145 138 120 147
 110 147 143 114 143 143 116 140 144 120 137 144 124 135 145 127 131 146
 131 127 147 135 124 150 107 150 144 110 147 145 113 143 146 117 141 147
 120 137 149 125 134 150 129 131 151 132 127 152 105 153 148 107 150 149
 111 147 149 115 144 151 118 141 151 122 138 152 126 135 154 130 131 156
 101 156 151 105 154 151 108 152 153 111 148 153 116 145 154 119 143 156
 123 138 157 127 135 158  99 160 154 102 157 154 106 155 155 109 152 156
 113 149 157 116 145 158 120 142 160 125 139 162]


In [2]:
#split11についてRGBからYCbCrに変換し、(データを間引いて、)離散コサイン変換 データ間引きはまた後日
split11_YCrCb = cv2.cvtColor(split11,cv2.COLOR_BGR2YCrCb)

#成分ごとに分割
split_Y, split_Cr, split_Cb = cv2.split(split11_YCrCb)

#離散コサイン変換
split_Y = split_Y.astype(np.float32)
split_Y_dct = cv2.dct(split_Y)
split_Y_idct = cv2.idct(split_Y_dct)

split_Cr = split_Cr.astype(np.float32)
split_Cr_dct = cv2.dct(split_Cr)
split_Cr_idct = cv2.idct(split_Cr_dct)

split_Cb = split_Cb.astype(np.float32)
split_Cb_dct = cv2.dct(split_Cb)
split_Cb_idct = cv2.idct(split_Cb_dct)

print(split_Cr_dct)

split_Y_idct = split_Y_idct.astype(np.uint8)
split_Cr_idct = split_Cr_idct.astype(np.uint8)
split_Cb_idct = split_Cb_idct.astype(np.uint8)



[[ 1.0731250e+03 -2.8743267e+01  2.1231649e+00 -2.3604069e+00
   6.2500000e-01 -4.3232948e-01  8.7944376e-01 -6.0600460e-02]
 [-4.0392890e+00  2.3334372e-01  2.9025629e-01  6.2749261e-01
  -1.6936150e-01 -2.6836547e-01  3.3283564e-01  8.5433745e-01]
 [-1.6332038e-01  3.9399472e-01  3.9016509e-01  4.9003175e-01
   2.1936306e-01  4.4249111e-01 -3.3838835e-01 -1.9174699e-02]
 [-2.5930232e-01  4.3353498e-01 -5.3261113e-01 -3.3957320e-01
   7.7066764e-02 -2.7092275e-01  1.5471552e-01 -3.4343827e-01]
 [-3.7500000e-01  4.7610712e-01  1.6332038e-01 -6.5283930e-01
   1.2500000e-01  7.7066742e-02  6.7649528e-02  1.6936134e-01]
 [-5.9847534e-01  2.7021486e-01  3.6968090e-02 -4.7802955e-01
   6.5283918e-01  7.3601973e-01 -5.9345141e-02  5.0675875e-01]
 [-6.7649513e-02 -3.1045851e-01  1.6161168e-01 -6.3985783e-01
   8.5623002e-01 -7.0532441e-01 -1.4016505e-01  1.7374085e-01]
 [-4.4298461e-01 -3.5276952e-01 -2.7530444e-01  6.9514221e-01
   4.7610748e-01  2.0071597e-01  2.0415480e-01  8.7021011e-01]]

In [3]:
#量子化
ryoshi_Y = np.array([[16,  11,  10,  16,  24,  40,  51,  61 ],
[ 12,  12,  14,  19,  26,  58,  60,  55 ],
[ 14,  13,  16,  24,  40,  57,  69,  56 ],
[ 14,  17,  22,  29,  51,  87,  80,  62 ],
[ 18,  22,  37,  56,  68, 109, 103,  77 ],
[ 24,  35,  55,  64,  81, 104, 113,  92 ],
[ 49,  64,  78,  87, 103, 121, 120, 101 ],
[ 72,  92,  95,  98, 112, 100, 103,  99 ]])

ryoshi_C = np.array([[17,  18,  24,  47,  99,  99,  99 , 99 ],
[ 18,  21,  26,  66,  99,  99,  99,  99 ],
[ 24,  26,  56,  99,  99,  99,  99,  99 ],
[ 47,  66,  99,  99,  99,  99,  99,  99 ],
[ 99,  99,  99,  99,  99,  99,  99,  99 ],
[ 99,  99,  99,  99,  99,  99,  99,  99 ],
[ 99,  99,  99,  99,  99,  99,  99,  99 ],
[ 99,  99,  99,  99,  99,  99,  99,  99 ]])


#Yを量子化、IDCT
split_Y_ryoshi = split_Y_dct/ryoshi_Y
split_Y_ryoshi = split_Y_ryoshi.astype(np.int8)
split_Y_ryoshi = split_Y_ryoshi*ryoshi_Y

split_Y_ryoshi = split_Y_ryoshi.astype(np.float32)
split_Y_idct = cv2.idct(split_Y_ryoshi)
split_Y_idct= split_Y_idct.astype(np.uint8)

#Crを量子化、IDCT
split_Cr_ryoshi = split_Cr_dct/ryoshi_C
split_Cr_ryoshi = split_Cr_ryoshi.astype(np.int8)
split_Cr_ryoshi = split_Cr_ryoshi*ryoshi_C

split_Cr_ryoshi = split_Cr_ryoshi.astype(np.float32)
split_Cr_idct = cv2.idct(split_Cr_ryoshi)
split_Cr_idct= split_Cr_idct.astype(np.uint8)

#Cbを量子化、IDCT
split_Cb_ryoshi = split_Cb_dct/ryoshi_C
split_Cb_ryoshi = split_Cb_ryoshi.astype(np.int8)
split_Cb_ryoshi = split_Cb_ryoshi*ryoshi_C

split_Cb_ryoshi = split_Cb_ryoshi.astype(np.float32)
split_Cb_idct = cv2.idct(split_Cb_ryoshi)
split_Cb_idct= split_Cb_idct.astype(np.uint8)

print(split_Y_ryoshi)
print(split_Cb_ryoshi)
print(split_Cr_ryoshi)

merge_YCrCb = cv2.merge((split_Y_idct, split_Cr_idct, split_Cb_idct))
merge = cv2.cvtColor(merge_YCrCb,cv2.COLOR_YCrCb2BGR)


cv2.namedWindow("Image1", cv2.WINDOW_NORMAL)
cv2.imshow("Image1", split11)
cv2.namedWindow("Image2", cv2.WINDOW_NORMAL)
cv2.imshow("Image2", merge)
cv2.waitKey()




[[1104.   11.    0.    0.    0.    0.    0.    0.]
 [ -48.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.]]
[[935. -36.   0.   0.   0.   0.   0.   0.]
 [ 36.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.   0.   0.]]
[[1071.  -18.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0.    0.]
 [   0.    0.    0.    0.    0.    0.    0

-1